### ISSUE TITLE
tf-image running on TPU

### ISSUE THREAD

**Issue by chho-work** [Ximilar-com/tf-image#4]
Hi, 

Thanks for the library!  
I am new in TF library.
I would like to know if tf-image can be implemented on TPU and TF Records?  If yes, can you pls provide and example.  

Many thanks!

**Comment by liborvaneksw** [comment]
Hi,
thank you for your interest in tf-image!

I sorry, the library was not tested on TPU yet. 
As for the TFRecords - it is just a format for storing a sequence of binary records. You need to parse those records and decode the images. (Please check documentation for that.) Then you can use tf-image functions as you would any other TensorFlow operation on images.

You can see some examples of using tf-image in README and in this article: [TensorFlow and Image Augmentation](https://towardsdatascience.com/tensorflow-and-image-augmentation-3610c6c243a2).

Did this help you at least a bit?
