### ISSUE TITLE
Segmentation mask rotation

### ISSUE THREAD

**Issue by VictorAtPL** [Ximilar-com/tf-image#5]
Thank you for you contribution.

I am training Mask-RCNN model and I have a CPU bottleneck. I had to move from passing data via generators to `tf.data`. Unfortunately, now I do not have a possibility to do image augmentation (implementation of model which uses generators also uses `imgaug` library).

I found your library, and I would like to add a data augmentation also for segmentation masks (beside bounding boxes).

1. Do I understand correctly that I need mainly to make changes in `tf_image.core.bboxes.rotate.random_rotate`?
2. Are all operations made by your library fully processed on GPU, so there will not be increase in CPU utilization?

**Comment by liborvaneksw** [comment]
Thank you for your interest in our library!

You can use `imgaug` with `tf.data`. Check [tf.py_function](https://www.tensorflow.org/api_docs/python/tf/py_function). And to your questions:

1. This library does not support segmentation "by default". The function you've mentioned is for rotating image + bounding boxes. (That means for object detection.) But it is not that difficult to implement this kind of augmentation for segmentation if you really want to. You just need to rotate your image and mask by the same (random) angle.

2. Unfortunately TensorFlow runs `tf.data.Dataset` operations on CPU at the moment, no matter the implementation. They are run in parallel with model training which is done on GPU (if available). Therefore if the augmentation takes longer than a training itself, the GPU will be idle for some time. (I'm sure you know about this, bur for the others - I recommend you to use [TensorBoard Profiler](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras) to find out where the bottle neck is.

**Comment by VictorAtPL** [comment]
> You can use `imgaug` with `tf.data`. Check [tf.py_function](https://www.tensorflow.org/api_docs/python/tf/py_function).

Yes, that's right. I've implemented integrated `imgaug` with `py_function`, but the utilization of CPU still isn't 100%.

> 1. This library does not support segmentation "by default". The function you've mentioned is for rotating image + bounding boxes. (That means for object detection.) But it is not that difficult to implement this kind of augmentation for segmentation if you really want to. You just need to rotate your image and mask by the same (random) angle.

That's what I wanted to now.

> 2. Unfortunately TensorFlow runs `tf.data.Dataset` operations on CPU at the moment, no matter the implementation. They are run in parallel with model training which is done on GPU (if available). Therefore if the augmentation takes longer than a training itself, the GPU will be idle for some time. (I'm sure you know about this, bur for the others - I recommend you to use [TensorBoard Profiler](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras) to find out where the bottle neck is.

That's interesting! I thought that if I use pure `tf.*` functions, it will run on GPU and offload CPU. I also heard about profiler in Tensorflow, but it's still up to check.

Thank you for your response!
